[dependencies]
pyo3 = {version = "0.21.2", features = ["extension-module"]}
image = "0.25.1"
serde = "1.0.198"
pdfium-render = "0.8.20"
rayon = "1.10.0"

[lib]
name = "docprompt_rs"
crate-type = ["cdylib"]

[package]
name = "docprompt_rs"
version = "0.1.0"
edition = "2021"
